# Generated by Django 5.2.13 on 2026-04-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIBKRExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(default='ibkr', max_length=20)),
                ('execution_id', models.CharField(blank=True, max_length=128, null=True)),
                ('perm_id', models.CharField(blank=True, max_length=128, null=True)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('client_id', models.CharField(blank=True, max_length=128, null=True)),
                ('account', models.CharField(blank=True, max_length=64, null=True)),
                ('symbol', models.CharField(max_length=64)),
                ('local_symbol', models.CharField(blank=True, max_length=64, null=True)),
                ('conid', models.CharField(blank=True, max_length=64, null=True)),
                ('sec_type', models.CharField(blank=True, max_length=32, null=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('exchange', models.CharField(blank=True, max_length=64, null=True)),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('commission', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('executed_at', models.DateTimeField()),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syncs.syncjob')),
            ],
            options={
                'ordering': ['executed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_at', models.DateTimeField()),
                ('commission', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('signed_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('asset_class', models.CharField(blank=True, max_length=32, null=True)),
                ('trade_day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill', to='trades.rawibkrexecution')),
            ],
            options={
                'ordering': ['executed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('trade_date', models.DateField()),
                ('asset_class', models.CharField(blank=True, max_length=32, null=True)),
                ('direction', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('closed', 'Closed')], default='open', max_length=20)),
                ('total_buy_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_sell_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('net_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('avg_buy_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('avg_sell_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('avg_open_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('open_qty', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('commission_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trade_date', '-id'],
                'unique_together': {('symbol', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='TradeLotSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=64)),
                ('open_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('remaining_qty', models.DecimalField(decimal_places=6, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_snapshots', to='trades.tradegroup')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawibkrexecution',
            index=models.Index(fields=['symbol', 'executed_at'], name='trades_rawi_symbol_227fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='rawibkrexecution',
            index=models.Index(fields=['trade_date'], name='trades_rawi_trade_d_a5700b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawibkrexecution',
            index=models.Index(fields=['perm_id'], name='trades_rawi_perm_id_d4d5f2_idx'),
        ),
    ]
