# Generated by Django 5.2.13 on 2026-04-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tradegroup",
            unique_together=set(),
        ),
    ]
