# Generated by Django 5.2.13 on 2026-04-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(unique=True)),
                ('market_summary', models.TextField(blank=True, default='')),
                ('emotions', models.TextField(blank=True, default='')),
                ('lessons', models.TextField(blank=True, default='')),
                ('next_day_plan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='MistakeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(default='red', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SetupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(default='blue', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.TextField(blank=True, default='')),
                ('execution_notes', models.TextField(blank=True, default='')),
                ('exit_notes', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='trades.tradegroup')),
            ],
        ),
    ]
