# Generated by Django 5.2.13 on 2026-04-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_dailyreview_image_and_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journal.dailyreview')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
