# Generated by Django 5.2.13 on 2026-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_dailyreviewimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradejournal",
            name="tv_snapshot_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
