# Generated by Django 5.2.13 on 2026-04-23 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_dailyreview_strategy_and_trade_logic"),
        ("trades", "0004_tradematchedlot"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreview",
            name="biggest_mistake",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="daily_bias",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="discipline_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="emotional_control_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="key_levels_catalyst",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="market_regime",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="max_daily_loss_respected",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="related_trade_groups",
            field=models.ManyToManyField(
                blank=True, related_name="daily_review_links", to="trades.tradegroup"
            ),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="watchlist",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="PositionCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reduced", "Reduced"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("carry_reason", models.TextField(blank=True, default="")),
                ("gap_risk_note", models.TextField(blank=True, default="")),
                ("thesis_update", models.TextField(blank=True, default="")),
                ("next_session_plan", models.TextField(blank=True, default="")),
                (
                    "exit_condition_unchanged",
                    models.BooleanField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_checkpoints",
                        to="trades.tradegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy", models.CharField(blank=True, default="", max_length=128)),
                ("session", models.CharField(blank=True, default="", max_length=32)),
                ("thesis", models.TextField(blank=True, default="")),
                ("entry_trigger", models.TextField(blank=True, default="")),
                ("invalidation", models.TextField(blank=True, default="")),
                ("planned_target", models.TextField(blank=True, default="")),
                ("sizing_rationale", models.TextField(blank=True, default="")),
                (
                    "entry_quality",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "exit_quality",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "risk_management",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("followed_plan", models.BooleanField(blank=True, null=True)),
                (
                    "emotion_before",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "emotion_during",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "emotion_after",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("what_i_did_well", models.TextField(blank=True, default="")),
                ("what_to_improve", models.TextField(blank=True, default="")),
                (
                    "realized_r",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "final_grade",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        default="",
                        max_length=2,
                    ),
                ),
                ("screenshots", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_reviews",
                        to="journal.dailyreview",
                    ),
                ),
                (
                    "mistake_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trade_reviews",
                        to="journal.mistaketag",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_reviews",
                        to="journal.setuptag",
                    ),
                ),
                (
                    "trade_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_review",
                        to="trades.tradegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
