# Generated by Django 5.2.13 on 2026-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_dailyreview_biggest_mistake_dailyreview_daily_bias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreview",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="market_condition",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="mistake_tags",
            field=models.ManyToManyField(
                blank=True, related_name="daily_reviews", to="journal.mistaketag"
            ),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="rule_followed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="session",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="trade_quality_grade",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="would_take_again",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
