# Generated by Django 5.2.13 on 2026-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0008_dailyreview_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradereview",
            name="would_take_again",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
