# Generated by Django 5.2.13 on 2026-04-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_tradereview_would_take_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreview",
            name="review_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("completed", "Completed")],
                default="draft",
                max_length=16,
            ),
        ),
    ]
