# Generated by Django 5.2.13 on 2026-04-23 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0010_dailyreview_review_status"),
        ("trades", "0004_tradematchedlot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreTradePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("premarket", "Premarket"),
                            ("open", "Open"),
                            ("midday", "Midday"),
                            ("close", "Close"),
                        ],
                        default="premarket",
                        max_length=16,
                    ),
                ),
                (
                    "market_regime",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("watchlist", models.JSONField(blank=True, default=list)),
                ("catalysts", models.TextField(blank=True, default="")),
                ("game_plan", models.TextField(blank=True, default="")),
                ("pre_trade_checklist", models.JSONField(blank=True, default=dict)),
                (
                    "risk_budget_r",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-plan_date", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="tradereview",
            name="mistake_severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tradereview",
            name="primary_mistake_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("discipline", "Discipline"),
                    ("execution", "Execution"),
                    ("risk", "Risk"),
                    ("strategy", "Strategy"),
                    ("psychology", "Psychology"),
                    ("process", "Process"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="tradereview",
            name="rule_violation_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("entry_rule", "Entry Rule"),
                    ("risk_rule", "Risk Rule"),
                    ("exit_rule", "Exit Rule"),
                    ("size_rule", "Size Rule"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SetupSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("strategy", models.CharField(blank=True, default="", max_length=128)),
                ("trigger_condition", models.TextField(blank=True, default="")),
                ("invalidation", models.TextField(blank=True, default="")),
                (
                    "planned_entry",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "planned_stop",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "planned_target",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("checklist_passed", models.BooleanField(default=False)),
                ("snapshot_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pretrade_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_snapshots",
                        to="journal.pretradeplan",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setup_snapshots",
                        to="journal.setuptag",
                    ),
                ),
                (
                    "trade_group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pretrade_snapshot",
                        to="trades.tradegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
