# Generated by Django 5.2.13 on 2026-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0011_pretradeplan_tradereview_mistake_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setupsnapshot",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="setupsnapshot",
            name="direction",
            field=models.CharField(
                choices=[("long", "Long"), ("short", "Short")],
                default="long",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="setupsnapshot",
            name="invalidation_type",
            field=models.CharField(
                choices=[
                    ("lose_vwap", "Lose VWAP"),
                    ("fail_breakout_2m", "Fail breakout within 2min"),
                    ("break_structure", "Break structure"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="setupsnapshot",
            name="setup_type",
            field=models.CharField(
                choices=[
                    ("breakout", "Breakout"),
                    ("pullback", "Pullback"),
                    ("reversal", "Reversal"),
                    ("range", "Range"),
                ],
                default="breakout",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="setupsnapshot",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("1m", "1m"),
                    ("5m", "5m"),
                    ("15m", "15m"),
                    ("1h", "1h"),
                    ("1d", "1d"),
                ],
                default="5m",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="setupsnapshot",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("break_premarket_high", "Break above premarket high"),
                    ("volume_spike", "Volume spike"),
                    ("vwap_reclaim", "VWAP reclaim"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
