# Generated by Django 5.2.13 on 2026-04-24 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0012_setupsnapshot_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreview",
            name="focus_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="positioncheckpoint",
            name="action_bias",
            field=models.CharField(default="hold", max_length=20),
        ),
        migrations.AddField(
            model_name="positioncheckpoint",
            name="checkpoint_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="positioncheckpoint",
            name="emotion_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
