# Generated by Django 5.2.13 on 2026-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0013_dailyreview_focus_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setupsnapshot",
            name="planned_risk_r",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
